apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 9092
          - containerPort: 9093
        env:
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service.default # Using kubernetes default DNS to reach zookeeper
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service

spec:
  selector:
    app: kafka-service
  ports:
    - name: port1
      port: 9092
      targetPort: 9092
    - name: port2
      port: 9093
      targetPort: 9093
