apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j 
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.2.3 # Pull from dockerhub
        ports:
          - containerPort: 7474
          - containerPort: 7687
        env:
          - name: NEO4J_AUTH
            value: "neo4j/some_password"
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
    - name: port1
      port: 7474
      targetPort: 7474
    - name: port2
      port: 7687
      targetPort: 7687
