apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer-app
          image: ronny1111/kub-demo-users 
          env:
            - name: KAFKA_BROKER
              value: kafka-service.default' #Connect to kafka default domain

      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer-app
  type: LoadBalancer # IP visible outside the cluster
  ports:
    - port: 80
      targetPort: 80
